up

diff --git a/bin/Pool b/bin/Pool
--- a/bin/Pool
+++ b/bin/Pool
@@ -16,17 +16,23 @@ do command -v "$c" >/dev/null
 done
 
 err=${TMPDIR:-/tmp}/err.$$
-out=${TMPDIR:-/tmp}/pool.$$
-trap 'rm -f "$out" "$err"' 0
+trap 'rm -f "$err"' 0
 trap 'exit 1' 1 2 15
 
 t=`/bin/date +%m/%d | /usr/bin/sed 's|^0||; s|/0|/|'`
 
-"$LYNX" -dump "$URL" > "$out" 2>"$err"
-case $? in
-    0) ;;
-    *) die $? "download of facility hours failed" ;;
-esac
+mkdir -p "$HOME/.cache/Pool"
+out=$HOME/.cache/Pool/`/bin/date +%Y%m%d`
+
+if test ! -s "$out"
+then
+    rm -f "$HOME/.cache/Pool"/*
+    "$LYNX" -dump "$URL" > "$out" 2>"$err"
+    case $? in
+        0) ;;
+        *) rm -f "$out"; die $? "download of facility hours failed" ;;
+    esac
+fi
 
 /usr/bin/awk -v t="$t" '
 /MAC Pool +Blodgett Pool/ { print; f = 1; next }
